/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSecureRouteImport } from './routes/_app/_secure'
import { Route as AppContrastCheckerRouteImport } from './routes/_app/contrast-checker'
import { Route as AppDesignSystemsRouteImport } from './routes/_app/design-systems'
import { Route as AppSpacingRouteImport } from './routes/_app/spacing'
import { Route as AppTypographyRouteImport } from './routes/_app/typography'
import { Route as AppSecureFavoritesRouteImport } from './routes/_app/_secure/favorites'
import { Route as AppSecureMyLibraryRouteImport } from './routes/_app/_secure/my-library'
import { Route as AppPaletteGeneratorChar123PaletteIdChar125RouteImport } from './routes/_app/palette-generator/{-$paletteId}'
import { Route as AppPalettePaletteIdRouteImport } from './routes/_app/palette.$paletteId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSecureRoute = AppSecureRouteImport.update({
  id: '/_secure',
  getParentRoute: () => AppRoute,
} as any)
const AppContrastCheckerRoute = AppContrastCheckerRouteImport.update({
  id: '/contrast-checker',
  path: '/contrast-checker',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignSystemsRoute = AppDesignSystemsRouteImport.update({
  id: '/design-systems',
  path: '/design-systems',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacingRoute = AppSpacingRouteImport.update({
  id: '/spacing',
  path: '/spacing',
  getParentRoute: () => AppRoute,
} as any)
const AppTypographyRoute = AppTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => AppRoute,
} as any)
const AppSecureFavoritesRoute = AppSecureFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppSecureRoute,
} as any)
const AppSecureMyLibraryRoute = AppSecureMyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => AppSecureRoute,
} as any)
const AppPaletteGeneratorChar123PaletteIdChar125Route =
  AppPaletteGeneratorChar123PaletteIdChar125RouteImport.update({
    id: '/palette-generator/{-$paletteId}',
    path: '/palette-generator/{-$paletteId}',
    getParentRoute: () => AppRoute,
  } as any)
const AppPalettePaletteIdRoute = AppPalettePaletteIdRouteImport.update({
  id: '/palette/$paletteId',
  path: '/palette/$paletteId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/contrast-checker': typeof AppContrastCheckerRoute
  '/design-systems': typeof AppDesignSystemsRoute
  '/spacing': typeof AppSpacingRoute
  '/typography': typeof AppTypographyRoute
  '/favorites': typeof AppSecureFavoritesRoute
  '/my-library': typeof AppSecureMyLibraryRoute
  '/palette-generator/{-$paletteId}': typeof AppPaletteGeneratorChar123PaletteIdChar125Route
  '/palette/$paletteId': typeof AppPalettePaletteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/': typeof AppIndexRoute
  '/contrast-checker': typeof AppContrastCheckerRoute
  '/design-systems': typeof AppDesignSystemsRoute
  '/spacing': typeof AppSpacingRoute
  '/typography': typeof AppTypographyRoute
  '/favorites': typeof AppSecureFavoritesRoute
  '/my-library': typeof AppSecureMyLibraryRoute
  '/palette-generator/{-$paletteId}': typeof AppPaletteGeneratorChar123PaletteIdChar125Route
  '/palette/$paletteId': typeof AppPalettePaletteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/_secure': typeof AppSecureRouteWithChildren
  '/_app/contrast-checker': typeof AppContrastCheckerRoute
  '/_app/design-systems': typeof AppDesignSystemsRoute
  '/_app/spacing': typeof AppSpacingRoute
  '/_app/typography': typeof AppTypographyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_secure/favorites': typeof AppSecureFavoritesRoute
  '/_app/_secure/my-library': typeof AppSecureMyLibraryRoute
  '/_app/palette-generator/{-$paletteId}': typeof AppPaletteGeneratorChar123PaletteIdChar125Route
  '/_app/palette/$paletteId': typeof AppPalettePaletteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/contrast-checker'
    | '/design-systems'
    | '/spacing'
    | '/typography'
    | '/favorites'
    | '/my-library'
    | '/palette-generator/{-$paletteId}'
    | '/palette/$paletteId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/contrast-checker'
    | '/design-systems'
    | '/spacing'
    | '/typography'
    | '/favorites'
    | '/my-library'
    | '/palette-generator/{-$paletteId}'
    | '/palette/$paletteId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/sign-up'
    | '/_app/_secure'
    | '/_app/contrast-checker'
    | '/_app/design-systems'
    | '/_app/spacing'
    | '/_app/typography'
    | '/_app/'
    | '/_app/_secure/favorites'
    | '/_app/_secure/my-library'
    | '/_app/palette-generator/{-$paletteId}'
    | '/_app/palette/$paletteId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_secure': {
      id: '/_app/_secure'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSecureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contrast-checker': {
      id: '/_app/contrast-checker'
      path: '/contrast-checker'
      fullPath: '/contrast-checker'
      preLoaderRoute: typeof AppContrastCheckerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design-systems': {
      id: '/_app/design-systems'
      path: '/design-systems'
      fullPath: '/design-systems'
      preLoaderRoute: typeof AppDesignSystemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spacing': {
      id: '/_app/spacing'
      path: '/spacing'
      fullPath: '/spacing'
      preLoaderRoute: typeof AppSpacingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/typography': {
      id: '/_app/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof AppTypographyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_secure/favorites': {
      id: '/_app/_secure/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppSecureFavoritesRouteImport
      parentRoute: typeof AppSecureRoute
    }
    '/_app/_secure/my-library': {
      id: '/_app/_secure/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof AppSecureMyLibraryRouteImport
      parentRoute: typeof AppSecureRoute
    }
    '/_app/palette-generator/{-$paletteId}': {
      id: '/_app/palette-generator/{-$paletteId}'
      path: '/palette-generator/{-$paletteId}'
      fullPath: '/palette-generator/{-$paletteId}'
      preLoaderRoute: typeof AppPaletteGeneratorChar123PaletteIdChar125RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/palette/$paletteId': {
      id: '/_app/palette/$paletteId'
      path: '/palette/$paletteId'
      fullPath: '/palette/$paletteId'
      preLoaderRoute: typeof AppPalettePaletteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSecureRouteChildren {
  AppSecureFavoritesRoute: typeof AppSecureFavoritesRoute
  AppSecureMyLibraryRoute: typeof AppSecureMyLibraryRoute
}

const AppSecureRouteChildren: AppSecureRouteChildren = {
  AppSecureFavoritesRoute: AppSecureFavoritesRoute,
  AppSecureMyLibraryRoute: AppSecureMyLibraryRoute,
}

const AppSecureRouteWithChildren = AppSecureRoute._addFileChildren(
  AppSecureRouteChildren,
)

interface AppRouteChildren {
  AppSecureRoute: typeof AppSecureRouteWithChildren
  AppContrastCheckerRoute: typeof AppContrastCheckerRoute
  AppDesignSystemsRoute: typeof AppDesignSystemsRoute
  AppSpacingRoute: typeof AppSpacingRoute
  AppTypographyRoute: typeof AppTypographyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPaletteGeneratorChar123PaletteIdChar125Route: typeof AppPaletteGeneratorChar123PaletteIdChar125Route
  AppPalettePaletteIdRoute: typeof AppPalettePaletteIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSecureRoute: AppSecureRouteWithChildren,
  AppContrastCheckerRoute: AppContrastCheckerRoute,
  AppDesignSystemsRoute: AppDesignSystemsRoute,
  AppSpacingRoute: AppSpacingRoute,
  AppTypographyRoute: AppTypographyRoute,
  AppIndexRoute: AppIndexRoute,
  AppPaletteGeneratorChar123PaletteIdChar125Route:
    AppPaletteGeneratorChar123PaletteIdChar125Route,
  AppPalettePaletteIdRoute: AppPalettePaletteIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
