name: Format, Lint, Test, Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format code
        run: pnpm fmt

      - name: Lint code
        run: pnpm lint

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run tests
        run: pnpm test

      - name: Build project
        run: pnpm build
